In [1]:
import scipy.io as sio

In [2]:
matDir = '/home/lerko/Downloads/Big_ALMA'
matName = 'datos_HD142_case1_26_05_17.mat'
matPath = matDir + '/' + matName
sio.loadmat(matPath)

{'Az0': array([[ 209.10208748]]),
 'El0': array([[ 9.74425989]]),
 'RA': array([[ 57.29577951]]),
 '__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri May 26 11:50:29 2017',
 '__version__': '1.0',
 'ant1': array([[ 0],
        [ 0],
        [ 0],
        ..., 
        [38],
        [39],
        [39]], dtype=uint8),
 'ant2': array([[ 1],
        [ 2],
        [ 3],
        ..., 
        [40],
        [40],
        [40]], dtype=uint8),
 'antennas': array([[array([[0]], dtype=uint8), array([[ 2225094.796703]]),
         array([[-5440052.421785]]), array([[-2481687.277348]]),
         array(['DA41'], 
       dtype='<U4'),
         array(['A004'], 
       dtype='<U4'), array([[12]], dtype=uint8),
         array([[0]], dtype=uint8)],
        [array([[1]], dtype=uint8), array([[ 2225181.07069]]),
         array([[-5440026.291678]]), array([[-2481662.97522]]),
         array(['DA42'], 
       dtype='<U4'),
         array(['A067'], 
       dtype='<U4'), 

In [5]:
import sqlite3 as sql
import pandas as pd

In [9]:
sqlDir = '/home/lerko/Downloads/Big_ALMA'
sqlName = 'HD142_b7_spw0_tav_bin.selfcal.sqlite'
sqlPath = sqlDir + '/' + sqlName

conn = sql.connect(sqlPath)
c = conn.cursor()
c.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = c.fetchall()

data = []

for t in tables:
    t = t[0]
    data.append(pd.read_sql_query("SELECT * from %s" % t, conn) )

In [16]:
#print(data[6])

In [17]:
import theano
import theano.tensor as tt
import numpy as np

A = theano.shared(2*np.ones((3,2)))
print(A.eval())
print('---------------')
B = theano.shared(0.5*np.ones((5,2)))
print(B.eval())

print('---------------')
print(tt.dot(A,B.T).eval())
print('---------------')
print(tt.mul(A,A).eval())

[[ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]]
---------------
[[ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]]
---------------
[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
---------------
[[ 4.  4.]
 [ 4.  4.]
 [ 4.  4.]]
